# # Joint State Controller
# joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50

# Franka Arm Controller
## hardware_interface: "hardware_interface::PositionJointInterface"
arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    constraints:
        goal_time: 0.5
        panda_joint1: { goal: 0.05}
        panda_joint2: { goal: 0.05}
        panda_joint3: { goal: 0.05}
        panda_joint4: { goal: 0.05}
        panda_joint5: { goal: 0.05}
        panda_joint6: { goal: 0.05}
        panda_joint7: { goal: 0.05}

# Allegro Hand Controller
hand_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - allegro_joint_0
        - allegro_joint_1
        - allegro_joint_2
        - allegro_joint_3
        - allegro_joint_4
        - allegro_joint_5
        - allegro_joint_6
        - allegro_joint_7
        - allegro_joint_8
        - allegro_joint_9
        - allegro_joint_10
        - allegro_joint_11
        - allegro_joint_12
        - allegro_joint_13
        - allegro_joint_14
        - allegro_joint_15
    constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.05
    state_publish_rate: 50
    publish_joint_states: true
    joint_states_publish_topic: /allegro_states
    action_monitor_rate: 20