move_group_name: "panda_arm"
planning_frame: "panda_link0"
ee_frame_name: "panda_link8"
robot_link_command_frame: "panda_link8"

joint_topic: "/joint_states" 
command_in_type: "speed_units"
cartesian_command_in_topic: "delta_twist_cmds"
joint_command_in_topic: "delta_joint_cmds"
command_out_topic: "/position_joint_trajectory_controller/command"
command_out_type: "trajectory_msgs/JointTrajectory"

publish_period: 0.008 
scale:
  linear: 0.6
  rotational: 0.3
  joint: 0.01
low_pass_filter_coeff: 5.0
check_collisions: false
collision_check_rate: 50.0
collision_check_type: "threshold_distance"
self_collision_proximity_threshold: 0.05
scene_collision_proximity_threshold: 0.1
collision_distance_safety_factor: 1.0
min_allowable_collision_distance: 0.01

publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false

joint_topic: joint_states
status_topic: "status"
warning_topic: "warnings"
incoming_command_timeout: 0.5

lower_singularity_threshold: 10.0
hard_stop_singularity_threshold: 20.0
joint_limit_margin: 0.2
use_gazebo: false
num_outgoing_halt_msgs_to_publish: 4

low_latency_mode: true
